// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package outboxdb

import (
	"context"
	"time"
)

const accept = `-- name: Accept :one
INSERT INTO outbox (id, tenant_id, provider, delivery_id, ordering_key, raw_body)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (tenant_id, delivery_id) DO NOTHING
RETURNING id
`

type AcceptParams struct {
	ID          string
	TenantID    string
	Provider    string
	DeliveryID  string
	OrderingKey string
	RawBody     []byte
}

// Runs bound to the tenant that owns the verified subscription. A repeated delivery returns no row.
func (q *Queries) Accept(ctx context.Context, arg AcceptParams) (string, error) {
	row := q.db.QueryRow(ctx, accept,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.DeliveryID,
		arg.OrderingKey,
		arg.RawBody,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const claim = `-- name: Claim :many
UPDATE outbox o
   SET lease_until = now() + make_interval(secs => $1::float8),
       lease_token = $2::text,
       attempts    = o.attempts + 1
  FROM (
        SELECT c.id
          FROM outbox c
          JOIN (
                SELECT DISTINCT ON (tenant_id, ordering_key) id
                  FROM outbox
                 WHERE state IN ('pending', 'prepared')
                 ORDER BY tenant_id, ordering_key, seq
               ) head ON head.id = c.id
         WHERE c.state IN ('pending', 'prepared')
           AND c.next_attempt_at <= now()
           AND (c.lease_until IS NULL OR c.lease_until < now())
         ORDER BY c.seq
         LIMIT $3
           FOR UPDATE OF c SKIP LOCKED
       ) claimed
 WHERE o.id = claimed.id
RETURNING o.id, o.tenant_id, o.attempts
`

type ClaimParams struct {
	LeaseSeconds float64
	LeaseToken   string
	BatchSize    int32
}

type ClaimRow struct {
	ID       string
	TenantID string
	Attempts int32
}

// Runs as the worker role, across tenants. Only the HEAD of each ordering key is ever eligible:
// the earliest unfinished row. If the head is leased or waiting out a backoff, nothing behind it
// moves, which is what keeps one entity's versions in arrival order.
//
// The state and lease conditions are repeated on the locked row itself, so that a row another
// claimer changed between this statement's snapshot and its lock is re-checked, not trusted.
func (q *Queries) Claim(ctx context.Context, arg ClaimParams) ([]ClaimRow, error) {
	rows, err := q.db.Query(ctx, claim, arg.LeaseSeconds, arg.LeaseToken, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimRow
	for rows.Next() {
		var i ClaimRow
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Attempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get = `-- name: Get :one
SELECT id, seq, tenant_id, provider, delivery_id, ordering_key, raw_body, state, attempts,
       next_attempt_at, lease_until, last_error, dead_reason, accepted_at, finished_at
  FROM outbox
 WHERE id = $1
`

type GetRow struct {
	ID            string
	Seq           int64
	TenantID      string
	Provider      string
	DeliveryID    string
	OrderingKey   string
	RawBody       []byte
	State         string
	Attempts      int32
	NextAttemptAt time.Time
	LeaseUntil    *time.Time
	LastError     string
	DeadReason    string
	AcceptedAt    time.Time
	FinishedAt    *time.Time
}

func (q *Queries) Get(ctx context.Context, id string) (GetRow, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i GetRow
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.TenantID,
		&i.Provider,
		&i.DeliveryID,
		&i.OrderingKey,
		&i.RawBody,
		&i.State,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.DeadReason,
		&i.AcceptedAt,
		&i.FinishedAt,
	)
	return i, err
}

const markDead = `-- name: MarkDead :execrows
UPDATE outbox
   SET state = 'dead', dead_reason = $1, last_error = $2, finished_at = now(),
       lease_until = NULL, lease_token = NULL
 WHERE id = $3 AND lease_token = $4::text AND state IN ('pending', 'prepared')
`

type MarkDeadParams struct {
	DeadReason string
	LastError  string
	ID         string
	LeaseToken string
}

func (q *Queries) MarkDead(ctx context.Context, arg MarkDeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDead,
		arg.DeadReason,
		arg.LastError,
		arg.ID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markDelivered = `-- name: MarkDelivered :execrows
UPDATE outbox
   SET state = 'delivered', finished_at = now(), lease_until = NULL, lease_token = NULL, last_error = ''
 WHERE id = $1 AND lease_token = $2::text AND state IN ('pending', 'prepared')
`

type MarkDeliveredParams struct {
	ID         string
	LeaseToken string
}

func (q *Queries) MarkDelivered(ctx context.Context, arg MarkDeliveredParams) (int64, error) {
	result, err := q.db.Exec(ctx, markDelivered, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markPrepared = `-- name: MarkPrepared :execrows

UPDATE outbox SET state = 'prepared'
 WHERE id = $1 AND lease_token = $2::text AND state = 'pending'
`

type MarkPreparedParams struct {
	ID         string
	LeaseToken string
}

// The transitions below run bound to the row's tenant, and only for the holder of the current
// lease. A worker whose lease ran out and was taken over changes nothing.
func (q *Queries) MarkPrepared(ctx context.Context, arg MarkPreparedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPrepared, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replay = `-- name: Replay :execrows
UPDATE outbox
   SET state = 'pending', attempts = 0, next_attempt_at = now(), dead_reason = '', finished_at = NULL
 WHERE id = $1 AND state = 'dead'
`

// Dead letters are a row state, so replay is an UPDATE. The row keeps its seq: if newer versions
// of the entity were delivered meanwhile, the forward-only supersede chain handles the late arrival.
func (q *Queries) Replay(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, replay, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retry = `-- name: Retry :execrows
UPDATE outbox
   SET next_attempt_at = now() + make_interval(secs => $1::float8),
       last_error = $2, lease_until = NULL, lease_token = NULL
 WHERE id = $3 AND lease_token = $4::text AND state IN ('pending', 'prepared')
`

type RetryParams struct {
	DelaySeconds float64
	LastError    string
	ID           string
	LeaseToken   string
}

// The state is kept: a prepared row retries its delivery, it does not prepare again.
func (q *Queries) Retry(ctx context.Context, arg RetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, retry,
		arg.DelaySeconds,
		arg.LastError,
		arg.ID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
