// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package outboxdb

import (
	"context"
	"time"
)

const accept = `-- name: Accept :one
INSERT INTO outbox (id, tenant_id, provider, delivery_id, ordering_key, raw_body, is_head)
VALUES ($1, $2::text, $3, $4, $5::text, $6,
        NOT EXISTS (
          SELECT 1
            FROM outbox u
           WHERE u.tenant_id = $2::text
             AND u.ordering_key = $5::text
             AND u.state IN ('pending', 'prepared')
        ))
ON CONFLICT (tenant_id, delivery_id) DO NOTHING
RETURNING id
`

type AcceptParams struct {
	ID          string
	TenantID    string
	Provider    string
	DeliveryID  string
	OrderingKey string
	RawBody     []byte
}

// Runs bound to the tenant that owns the verified subscription, after LockOrderingKey. A repeated
// delivery returns no row. The row is the head of its key exactly when the key has no unfinished
// row: a probe of one key in outbox_unfinished, whatever the size of the table.
//
// The tenant and the key are used twice, so they are cast at every use: left to itself, Postgres
// deduces the tenant_id domain for one use and text for the other, and refuses the statement.
func (q *Queries) Accept(ctx context.Context, arg AcceptParams) (string, error) {
	row := q.db.QueryRow(ctx, accept,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.DeliveryID,
		arg.OrderingKey,
		arg.RawBody,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const claim = `-- name: Claim :many
UPDATE outbox o
   SET lease_until = now() + make_interval(secs => $1::float8),
       lease_token = $2::text,
       attempts    = o.attempts + 1
  FROM (
        SELECT c.id
          FROM outbox c
         WHERE c.is_head
           AND c.due_at <= now()
         ORDER BY c.due_at, c.seq
         LIMIT $3
           FOR UPDATE OF c SKIP LOCKED
       ) claimed
 WHERE o.id = claimed.id
RETURNING o.id, o.tenant_id, o.attempts
`

type ClaimParams struct {
	LeaseSeconds float64
	LeaseToken   string
	BatchSize    int32
}

type ClaimRow struct {
	ID       string
	TenantID string
	Attempts int32
}

// Runs as the worker role, across tenants. Only the HEAD of an ordering key is ever eligible, and
// being the head is a stored column (is_head), so this statement walks outbox_due_heads from its
// front and stops at the batch. It never visits a row behind a head, a head waiting out a backoff,
// or a head another worker holds (due_at covers both the backoff and the lease): the cost follows
// the batch, not the backlog. If the head is leased or backing off, nothing behind it moves,
// because nothing behind it is a head.
//
// The candidates are found on this statement's snapshot, but a row is leased on its LATEST
// version, which another transaction may have changed between the snapshot and the row lock.
// Postgres then re-evaluates the conditions below against that latest version, and both are
// conditions on the locked row itself, with no join whose other side could be stale:
//
//	is_head   the row may have finished and handed the marker on, or died and been replayed to
//	          the back of its queue behind a version that is in flight by now;
//	due_at    another claimer may have leased it meanwhile, or it may have been given a backoff.
//
// A leased row is therefore a head at lock time. outbox_one_head allows one head per key, and an
// unfinished row keeps the marker until it finishes, so no other row of the key can be in flight.
//
// There is deliberately no condition on the state. The table's CHECK makes every head unfinished,
// on every version of every row, so is_head says it all. Saying it again is not free: the planner
// takes is_head and the state for independent, expects a fraction of the heads there are, decides
// that walking the index to fill a batch of 100 would take too long, and ANDs in a bitmap of
// outbox_unfinished instead, which is every waiting row (measured: 100,000 index entries read to
// return 100 rows). Do not add one.
func (q *Queries) Claim(ctx context.Context, arg ClaimParams) ([]ClaimRow, error) {
	rows, err := q.db.Query(ctx, claim, arg.LeaseSeconds, arg.LeaseToken, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimRow
	for rows.Next() {
		var i ClaimRow
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Attempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get = `-- name: Get :one
SELECT id, seq, tenant_id, provider, delivery_id, ordering_key, raw_body, state, is_head, attempts,
       next_attempt_at, lease_until, last_error, dead_reason, accepted_at, prepared_at, finished_at
  FROM outbox
 WHERE id = $1
`

type GetRow struct {
	ID            string
	Seq           int64
	TenantID      string
	Provider      string
	DeliveryID    string
	OrderingKey   string
	RawBody       []byte
	State         string
	IsHead        bool
	Attempts      int32
	NextAttemptAt time.Time
	LeaseUntil    *time.Time
	LastError     string
	DeadReason    string
	AcceptedAt    time.Time
	PreparedAt    *time.Time
	FinishedAt    *time.Time
}

func (q *Queries) Get(ctx context.Context, id string) (GetRow, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i GetRow
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.TenantID,
		&i.Provider,
		&i.DeliveryID,
		&i.OrderingKey,
		&i.RawBody,
		&i.State,
		&i.IsHead,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.DeadReason,
		&i.AcceptedAt,
		&i.PreparedAt,
		&i.FinishedAt,
	)
	return i, err
}

const lockOrderingKey = `-- name: LockOrderingKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text || chr(31) || $2::text, 0))
`

type LockOrderingKeyParams struct {
	TenantID    string
	OrderingKey string
}

// Serializes every writer that changes which rows of one ordering key are unfinished, or which of
// them is the head: Accept, Replay, and the two transitions that finish a row (MarkDelivered,
// MarkDead). It does two jobs.
//
// Queue order. seq is assigned when the statement runs, not when it commits: without this lock, v1
// could be inserted first and commit last. The lock is held to the end of the transaction, so
// within one key, seq order is commit order.
//
// The head marker. Accept decides whether its row is the head by asking whether the key has an
// unfinished row, and a finishing transition hands the marker to the next unfinished row. Without
// the lock the two can miss each other: Accept sees v1 unfinished and inserts v2 as a non-head,
// while the MarkDelivered of v1 does not see the uncommitted v2 and promotes nothing. v2 would
// never be claimable. With the lock, one of them runs entirely after the other has committed.
//
// It must be its own statement, before the one that reads or writes the key's rows: under READ
// COMMITTED the next statement's snapshot is then taken after the previous holder committed. Two
// keys that hash alike only wait for each other, which is harmless. The claim never takes it.
func (q *Queries) LockOrderingKey(ctx context.Context, arg LockOrderingKeyParams) error {
	_, err := q.db.Exec(ctx, lockOrderingKey, arg.TenantID, arg.OrderingKey)
	return err
}

const lockOrderingKeyOf = `-- name: LockOrderingKeyOf :exec
SELECT pg_advisory_xact_lock(hashtextextended(tenant_id::text || chr(31) || ordering_key, 0))
  FROM outbox
 WHERE id = $1
`

// LockOrderingKey for a row known only by its id. Runs bound to the row's tenant, before Replay
// and before the finishing transitions. It reads the row without locking it (ordering_key never
// changes), so the advisory lock always comes before any row lock.
func (q *Queries) LockOrderingKeyOf(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, lockOrderingKeyOf, id)
	return err
}

const markDead = `-- name: MarkDead :one
UPDATE outbox
   SET state = 'dead', is_head = false, dead_reason = $1, last_error = $2,
       finished_at = now(), lease_until = NULL, lease_token = NULL
 WHERE id = $3 AND lease_token = $4::text AND state IN ('pending', 'prepared')
RETURNING ordering_key
`

type MarkDeadParams struct {
	DeadReason string
	LastError  string
	ID         string
	LeaseToken string
}

func (q *Queries) MarkDead(ctx context.Context, arg MarkDeadParams) (string, error) {
	row := q.db.QueryRow(ctx, markDead,
		arg.DeadReason,
		arg.LastError,
		arg.ID,
		arg.LeaseToken,
	)
	var ordering_key string
	err := row.Scan(&ordering_key)
	return ordering_key, err
}

const markDelivered = `-- name: MarkDelivered :one

UPDATE outbox
   SET state = 'delivered', is_head = false, finished_at = now(),
       lease_until = NULL, lease_token = NULL, last_error = ''
 WHERE id = $1 AND lease_token = $2::text AND state IN ('pending', 'prepared')
RETURNING ordering_key
`

type MarkDeliveredParams struct {
	ID         string
	LeaseToken string
}

// The two transitions that FINISH a row run after LockOrderingKeyOf and are followed, in the same
// transaction, by PromoteNextHead. They return the key to promote in. No row means the lease was
// lost, and then nothing is promoted.
func (q *Queries) MarkDelivered(ctx context.Context, arg MarkDeliveredParams) (string, error) {
	row := q.db.QueryRow(ctx, markDelivered, arg.ID, arg.LeaseToken)
	var ordering_key string
	err := row.Scan(&ordering_key)
	return ordering_key, err
}

const markPrepared = `-- name: MarkPrepared :execrows

UPDATE outbox SET state = 'prepared', prepared_at = now()
 WHERE id = $1 AND lease_token = $2::text AND state = 'pending'
`

type MarkPreparedParams struct {
	ID         string
	LeaseToken string
}

// The transitions below run bound to the row's tenant, and only for the holder of the current
// lease. A worker whose lease ran out and was taken over changes nothing.
func (q *Queries) MarkPrepared(ctx context.Context, arg MarkPreparedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPrepared, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const promoteNextHead = `-- name: PromoteNextHead :exec
UPDATE outbox
   SET is_head = true
 WHERE id = (
        SELECT n.id
          FROM outbox n
         WHERE n.tenant_id = $1::text
           AND n.ordering_key = $2::text
           AND n.state IN ('pending', 'prepared')
         ORDER BY n.seq
         LIMIT 1
       )
`

type PromoteNextHeadParams struct {
	TenantID    string
	OrderingKey string
}

// Hands the head marker to the earliest unfinished row of the key, if there is one. A statement of
// its own, after the one that finished the old head: the unique index on heads is checked row by
// row, so the old head has to be gone first, and this statement has to see that it is. Under the
// key's lock no Accept or Replay of the key is open, so the row chosen here really is the earliest.
func (q *Queries) PromoteNextHead(ctx context.Context, arg PromoteNextHeadParams) error {
	_, err := q.db.Exec(ctx, promoteNextHead, arg.TenantID, arg.OrderingKey)
	return err
}

const replay = `-- name: Replay :execrows
UPDATE outbox r
   SET seq = DEFAULT,
       state = CASE WHEN r.prepared_at IS NULL THEN 'pending' ELSE 'prepared' END,
       is_head = NOT EXISTS (
         SELECT 1
           FROM outbox u
          WHERE u.tenant_id = r.tenant_id
            AND u.ordering_key = r.ordering_key
            AND u.state IN ('pending', 'prepared')
       ),
       attempts = 0, next_attempt_at = now(), dead_reason = '', finished_at = NULL
 WHERE r.id = $1 AND r.state = 'dead'
`

// Dead letters are a row state, so replay is an UPDATE. Runs after LockOrderingKeyOf.
//
// The row goes to the BACK of its key's queue: it takes a fresh seq, exactly as if it had just
// been accepted, and like an accepted row it is the head only if its key has no unfinished row. A
// dead row does not hold back newer versions, so by the time it is replayed a newer version may be
// delivered, or in flight right now, and then the replayed row waits behind it. The replayed
// version is therefore delivered after every version accepted before the replay, and the
// forward-only supersede chain handles it like any other late arrival of an old version.
//
// A row that died after it was prepared goes back to prepared, not pending: its ledger rows and
// prepared records are committed, and a prepared row is never prepared again.
func (q *Queries) Replay(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, replay, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retry = `-- name: Retry :execrows
UPDATE outbox
   SET next_attempt_at = now() + make_interval(secs => $1::float8),
       last_error = $2, lease_until = NULL, lease_token = NULL
 WHERE id = $3 AND lease_token = $4::text AND state IN ('pending', 'prepared')
`

type RetryParams struct {
	DelaySeconds float64
	LastError    string
	ID           string
	LeaseToken   string
}

// The state is kept: a prepared row retries its delivery, it does not prepare again. The row stays
// the head of its key, so nothing behind it moves while it waits.
func (q *Queries) Retry(ctx context.Context, arg RetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, retry,
		arg.DelaySeconds,
		arg.LastError,
		arg.ID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
