// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package outboxdb

import (
	"context"
	"time"
)

const accept = `-- name: Accept :one
INSERT INTO outbox (id, tenant_id, provider, delivery_id, ordering_key, raw_body, is_head)
VALUES ($1, $2::text, $3, $4, $5::text, $6,
        NOT EXISTS (
          SELECT 1
            FROM outbox u
           WHERE u.tenant_id = $2::text
             AND u.ordering_key = $5::text
             AND u.state IN ('pending', 'prepared')
        ))
ON CONFLICT (tenant_id, delivery_id) DO NOTHING
RETURNING id
`

type AcceptParams struct {
	ID          string
	TenantID    string
	Provider    string
	DeliveryID  string
	OrderingKey string
	RawBody     []byte
}

// Runs bound to the tenant that owns the verified subscription, after LockOrderingKey. A repeated
// delivery returns no row. The row is the head of its key exactly when the key has no unfinished
// row: a probe of one key in outbox_unfinished, whatever the size of the table.
//
// The tenant and the key are used twice, so they are cast at every use: left to itself, Postgres
// deduces the tenant_id domain for one use and text for the other, and refuses the statement.
func (q *Queries) Accept(ctx context.Context, arg AcceptParams) (string, error) {
	row := q.db.QueryRow(ctx, accept,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.DeliveryID,
		arg.OrderingKey,
		arg.RawBody,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const claim = `-- name: Claim :many
UPDATE outbox o
   SET lease_until = now() + make_interval(secs => $1::float8),
       lease_token = $2::text,
       attempts    = o.attempts + 1
  FROM (
        SELECT c.id
          FROM outbox c
         WHERE c.is_head
           AND c.due_at <= now()
         ORDER BY c.due_at, c.seq
         LIMIT $3
           FOR UPDATE OF c SKIP LOCKED
       ) claimed
 WHERE o.id = claimed.id
RETURNING o.id, o.tenant_id, o.attempts
`

type ClaimParams struct {
	LeaseSeconds float64
	LeaseToken   string
	BatchSize    int32
}

type ClaimRow struct {
	ID       string
	TenantID string
	Attempts int32
}

// Runs as the worker role, across tenants. Only the HEAD of an ordering key is ever eligible, and
// being the head is a stored column (is_head), so this statement walks outbox_due_heads from its
// front and stops at the batch. It never visits a row behind a head, a head waiting out a backoff,
// or a head another worker holds (due_at covers both the backoff and the lease): the cost follows
// the batch, not the backlog. If the head is leased or backing off, nothing behind it moves,
// because nothing behind it is a head.
//
// The candidates are found on this statement's snapshot, but a row is leased on its LATEST
// version, which another transaction may have changed between the snapshot and the row lock.
// Postgres then re-evaluates the conditions below against that latest version, and both are
// conditions on the locked row itself, with no join whose other side could be stale:
//
//	is_head   the row may have finished and handed the marker on, or died and been replayed to
//	          the back of its queue behind a version that is in flight by now;
//	due_at    another claimer may have leased it meanwhile, or it may have been given a backoff.
//
// A leased row is therefore a head at lock time. outbox_one_head allows one head per key, and an
// unfinished row keeps the marker until it finishes, so no other row of the key can be in flight.
//
// There is deliberately no condition on the state. The table's CHECK makes every head unfinished,
// on every version of every row, so is_head says it all. Saying it again is not free: the planner
// takes is_head and the state for independent, expects a fraction of the heads there are, decides
// that walking the index to fill a batch of 100 would take too long, and ANDs in a bitmap of
// outbox_unfinished instead, which is every waiting row (measured: 100,000 index entries read to
// return 100 rows). Do not add one.
func (q *Queries) Claim(ctx context.Context, arg ClaimParams) ([]ClaimRow, error) {
	rows, err := q.db.Query(ctx, claim, arg.LeaseSeconds, arg.LeaseToken, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimRow
	for rows.Next() {
		var i ClaimRow
		if err := rows.Scan(&i.ID, &i.TenantID, &i.Attempts); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const get = `-- name: Get :one
SELECT id, seq, tenant_id, provider, delivery_id, ordering_key, raw_body, state, is_head, attempts,
       next_attempt_at, lease_until, last_error, dead_reason, accepted_at, prepared_at, finished_at
  FROM outbox
 WHERE id = $1
`

type GetRow struct {
	ID            string
	Seq           int64
	TenantID      string
	Provider      string
	DeliveryID    string
	OrderingKey   string
	RawBody       []byte
	State         string
	IsHead        bool
	Attempts      int32
	NextAttemptAt time.Time
	LeaseUntil    *time.Time
	LastError     string
	DeadReason    string
	AcceptedAt    time.Time
	PreparedAt    *time.Time
	FinishedAt    *time.Time
}

func (q *Queries) Get(ctx context.Context, id string) (GetRow, error) {
	row := q.db.QueryRow(ctx, get, id)
	var i GetRow
	err := row.Scan(
		&i.ID,
		&i.Seq,
		&i.TenantID,
		&i.Provider,
		&i.DeliveryID,
		&i.OrderingKey,
		&i.RawBody,
		&i.State,
		&i.IsHead,
		&i.Attempts,
		&i.NextAttemptAt,
		&i.LeaseUntil,
		&i.LastError,
		&i.DeadReason,
		&i.AcceptedAt,
		&i.PreparedAt,
		&i.FinishedAt,
	)
	return i, err
}

const halt = `-- name: Halt :execrows
UPDATE outbox
   SET next_attempt_at = now() + make_interval(secs => $1::float8),
       last_error = $2, lease_until = NULL, lease_token = NULL,
       attempts = GREATEST(attempts - 1, 0)
 WHERE id = $3 AND lease_token = $4::text AND state IN ('pending', 'prepared')
`

type HaltParams struct {
	PauseSeconds float64
	LastError    string
	ID           string
	LeaseToken   string
}

// A failure that the ladder must not walk: the sink refused the request itself, or Lawang could
// not even build the delivery (no sink for the tenant, a sink that broke its contract). The row
// keeps its state and its head marker, so nothing of its entity passes it, and it is claimable
// again after the pause.
//
// attempts goes back down, because this attempt is not one the ladder may count. Two things rest
// on that: Fail indexes the ladder by the attempt count, so a halting sink would otherwise walk
// the ladder to its end and dead-letter rows that architecture section 11 says must never be
// dead-lettered; and the drain parks a row whose attempts have run away from the ladder with no
// recorded failure, which a halt would otherwise trip.
func (q *Queries) Halt(ctx context.Context, arg HaltParams) (int64, error) {
	result, err := q.db.Exec(ctx, halt,
		arg.PauseSeconds,
		arg.LastError,
		arg.ID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const lockOrderingKey = `-- name: LockOrderingKey :exec
SELECT pg_advisory_xact_lock(
         hashtextextended($1::text || chr(31) || $2::text, 0) | (-9223372036854775808)::bigint)
`

type LockOrderingKeyParams struct {
	TenantID    string
	OrderingKey string
}

// Serializes every writer that changes which rows of one ordering key are unfinished, or which of
// them is the head: Accept, Replay, and the two transitions that finish a row (MarkDelivered,
// MarkDead). It does two jobs.
//
// Queue order. seq is assigned when the statement runs, not when it commits: without this lock, v1
// could be inserted first and commit last. The lock is held to the end of the transaction, so
// within one key, seq order is commit order.
//
// The head marker. Accept decides whether its row is the head by asking whether the key has an
// unfinished row, and a finishing transition hands the marker to the next unfinished row. Without
// the lock the two can miss each other: Accept sees v1 unfinished and inserts v2 as a non-head,
// while the MarkDelivered of v1 does not see the uncommitted v2 and promotes nothing. v2 would
// never be claimable. With the lock, one of them runs entirely after the other has committed.
//
// It must be its own statement, before the one that reads or writes the key's rows: under READ
// COMMITTED the next statement's snapshot is then taken after the previous holder committed. Under
// any other level it is not (the snapshot is the transaction's, from before the wait), and the two
// miss each other just the same. store begins every transaction READ COMMITTED by name for that
// reason, whatever default_transaction_isolation says. Two keys that hash alike only wait for each
// other, which is harmless. The claim never takes it.
//
// The high bit of the key is set, which puts every ordering-key lock in the negative half of
// Postgres's one advisory-lock namespace. internal/pipeline clears it, so its entity locks are
// the non-negative half, and an ordering-key value can never equal an entity-key value. That is
// what makes the cross-module rule ("ascending by key", see internal/pipeline/queries.sql and
// ADR 12 decision 1) a total order without assuming the two hashes never collide. Each half
// still holds 63 bits, and a collision WITHIN a half is a wait, not a deadlock.
func (q *Queries) LockOrderingKey(ctx context.Context, arg LockOrderingKeyParams) error {
	_, err := q.db.Exec(ctx, lockOrderingKey, arg.TenantID, arg.OrderingKey)
	return err
}

const lockOrderingKeyOf = `-- name: LockOrderingKeyOf :exec
SELECT pg_advisory_xact_lock(
         hashtextextended(tenant_id::text || chr(31) || ordering_key, 0) | (-9223372036854775808)::bigint)
  FROM outbox
 WHERE id = $1
`

// LockOrderingKey for a row known only by its id. Runs bound to the row's tenant, before Replay
// and before the finishing transitions. It reads the row without locking it (ordering_key never
// changes), so the advisory lock always comes before any row lock.
//
// The same key as LockOrderingKey, high bit and all: the two have to name one lock.
func (q *Queries) LockOrderingKeyOf(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, lockOrderingKeyOf, id)
	return err
}

const markDead = `-- name: MarkDead :one
UPDATE outbox
   SET state = 'dead', is_head = false, dead_reason = $1, last_error = $2,
       finished_at = now(), lease_until = NULL, lease_token = NULL
 WHERE id = $3 AND lease_token = $4::text AND state IN ('pending', 'prepared')
RETURNING ordering_key
`

type MarkDeadParams struct {
	DeadReason string
	LastError  string
	ID         string
	LeaseToken string
}

func (q *Queries) MarkDead(ctx context.Context, arg MarkDeadParams) (string, error) {
	row := q.db.QueryRow(ctx, markDead,
		arg.DeadReason,
		arg.LastError,
		arg.ID,
		arg.LeaseToken,
	)
	var ordering_key string
	err := row.Scan(&ordering_key)
	return ordering_key, err
}

const markDelivered = `-- name: MarkDelivered :one

UPDATE outbox
   SET state = 'delivered', is_head = false, finished_at = now(),
       lease_until = NULL, lease_token = NULL, last_error = ''
 WHERE id = $1 AND lease_token = $2::text AND state IN ('pending', 'prepared')
RETURNING ordering_key
`

type MarkDeliveredParams struct {
	ID         string
	LeaseToken string
}

// The two transitions that FINISH a row run after LockOrderingKeyOf and are followed, in the same
// transaction, by PromoteNextHead. They return the key to promote in. No row means the lease was
// lost, and then nothing is promoted.
func (q *Queries) MarkDelivered(ctx context.Context, arg MarkDeliveredParams) (string, error) {
	row := q.db.QueryRow(ctx, markDelivered, arg.ID, arg.LeaseToken)
	var ordering_key string
	err := row.Scan(&ordering_key)
	return ordering_key, err
}

const markPrepared = `-- name: MarkPrepared :execrows

UPDATE outbox SET state = 'prepared', prepared_at = now()
 WHERE id = $1 AND lease_token = $2::text AND state = 'pending'
`

type MarkPreparedParams struct {
	ID         string
	LeaseToken string
}

// The transitions below run bound to the row's tenant, and only for the holder of the current
// lease. A worker whose lease ran out and was taken over changes nothing.
func (q *Queries) MarkPrepared(ctx context.Context, arg MarkPreparedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markPrepared, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRecordDead = `-- name: MarkRecordDead :execrows
UPDATE outbox_record
   SET state = 'dead', dead_reason = $1, last_error = $2, finished_at = now()
 WHERE outbox_id = $3 AND record_id = $4 AND state = 'prepared'
`

type MarkRecordDeadParams struct {
	DeadReason string
	LastError  string
	OutboxID   string
	RecordID   string
}

// One record the sink refused. The rest of the batch is delivered by the statement below, in the
// same transaction, so a delivery with one refusal in it loses neither the dead letter nor the
// records that landed.
func (q *Queries) MarkRecordDead(ctx context.Context, arg MarkRecordDeadParams) (int64, error) {
	result, err := q.db.Exec(ctx, markRecordDead,
		arg.DeadReason,
		arg.LastError,
		arg.OutboxID,
		arg.RecordID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markRecordsDelivered = `-- name: MarkRecordsDelivered :exec
UPDATE outbox_record
   SET state = 'delivered', finished_at = now()
 WHERE outbox_id = $1 AND state = 'prepared'
`

// Every record of the delivery that is still open. It runs after MarkRecordDead has taken the
// refused ones out of that set, which is what makes "a record not named as refused was taken"
// true of what is stored.
func (q *Queries) MarkRecordsDelivered(ctx context.Context, outboxID string) error {
	_, err := q.db.Exec(ctx, markRecordsDelivered, outboxID)
	return err
}

const park = `-- name: Park :one
INSERT INTO outbox (id, tenant_id, provider, delivery_id, ordering_key, raw_body,
                    state, is_head, dead_reason, finished_at)
VALUES ($1, $2::text, $3, $4::text, $4::text, $5,
        'dead', false, $6, now())
ON CONFLICT (tenant_id, delivery_id) DO NOTHING
RETURNING id
`

type ParkParams struct {
	ID         string
	TenantID   string
	Provider   string
	DeliveryID string
	RawBody    []byte
	DeadReason string
}

// Stores a delivery nobody can be shown to own, under the sentinel tenant, already finished.
//
// It takes no advisory lock, and that is not an omission. The lock exists to keep queue order and
// the head marker within one ordering key, and a parked row has neither: it is inserted 'dead' and
// is_head false, so nothing ever claims it, nothing waits behind it, and the "is the key
// unfinished?" test that Accept and Replay make (which counts only pending and prepared rows)
// cannot see it. Its ordering key is its own delivery id, so no two parked rows share a key and a
// flood of unattributable deliveries queues on nothing at all.
//
// A repeated delivery returns no row, exactly as Accept does: the unique key is
// (tenant_id, delivery_id), and the sentinel is one tenant, so re-sending an unowned delivery
// parks it once.
func (q *Queries) Park(ctx context.Context, arg ParkParams) (string, error) {
	row := q.db.QueryRow(ctx, park,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.DeliveryID,
		arg.RawBody,
		arg.DeadReason,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const preparedRecords = `-- name: PreparedRecords :many
SELECT record_id, document, op, kind
  FROM outbox_record
 WHERE outbox_id = $1 AND state = 'prepared'
 ORDER BY pos
`

type PreparedRecordsRow struct {
	RecordID string
	Document []byte
	Op       string
	Kind     string
}

// What a claim of this delivery still has to deliver, in delivery order. A record that has
// already been delivered is not sent again, and a dead letter waits for a replay to bring it
// back, so a re-drain after a crash offers exactly what is left.
//
// op and kind come back with the document because record.Reopen needs them: they are in the
// record's seal and not in its id, so the document cannot be checked for them on its own.
func (q *Queries) PreparedRecords(ctx context.Context, outboxID string) ([]PreparedRecordsRow, error) {
	rows, err := q.db.Query(ctx, preparedRecords, outboxID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PreparedRecordsRow
	for rows.Next() {
		var i PreparedRecordsRow
		if err := rows.Scan(
			&i.RecordID,
			&i.Document,
			&i.Op,
			&i.Kind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteNextHead = `-- name: PromoteNextHead :exec
UPDATE outbox
   SET is_head = true
 WHERE id = (
        SELECT n.id
          FROM outbox n
         WHERE n.tenant_id = $1::text
           AND n.ordering_key = $2::text
           AND n.state IN ('pending', 'prepared')
         ORDER BY n.seq
         LIMIT 1
       )
`

type PromoteNextHeadParams struct {
	TenantID    string
	OrderingKey string
}

// Hands the head marker to the earliest unfinished row of the key, if there is one. A statement of
// its own, after the one that finished the old head: the unique index on heads is checked row by
// row, so the old head has to be gone first, and this statement has to see that it is. Under the
// key's lock no Accept or Replay of the key is open, so the row chosen here really is the earliest.
func (q *Queries) PromoteNextHead(ctx context.Context, arg PromoteNextHeadParams) error {
	_, err := q.db.Exec(ctx, promoteNextHead, arg.TenantID, arg.OrderingKey)
	return err
}

const release = `-- name: Release :execrows
UPDATE outbox
   SET lease_until = NULL, lease_token = NULL, attempts = GREATEST(attempts - 1, 0)
 WHERE id = $1 AND lease_token = $2::text AND state IN ('pending', 'prepared')
`

type ReleaseParams struct {
	ID         string
	LeaseToken string
}

// Gives a claimed row back without working it, for a worker that is shutting down: the lease is
// cleared, so another replica (or this one after a restart) can take it at once, and the attempt
// is given back, because nothing was attempted.
//
// Without it, a rolling restart would spend an attempt on every row a draining worker had
// claimed but not reached, and enough restarts in a row would walk a row past the end of its
// ladder and park it as abandoned although nothing was ever wrong with it.
func (q *Queries) Release(ctx context.Context, arg ReleaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, release, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replay = `-- name: Replay :execrows
UPDATE outbox r
   SET seq = DEFAULT,
       state = CASE WHEN r.prepared_at IS NULL THEN 'pending' ELSE 'prepared' END,
       is_head = NOT EXISTS (
         SELECT 1
           FROM outbox u
          WHERE u.tenant_id = r.tenant_id
            AND u.ordering_key = r.ordering_key
            AND u.state IN ('pending', 'prepared')
       ),
       attempts = 0, next_attempt_at = now(), dead_reason = '', finished_at = NULL
 WHERE r.id = $1
   AND (r.state = 'dead'
        OR (r.state = 'delivered'
            AND EXISTS (SELECT 1 FROM outbox_record x
                         WHERE x.outbox_id = r.id AND x.state = 'dead')))
`

// Dead letters are a row state, so replay is an UPDATE. Runs after LockOrderingKeyOf.
//
// The row goes to the BACK of its key's queue: it takes a fresh seq, exactly as if it had just
// been accepted, and like an accepted row it is the head only if its key has no unfinished row. A
// dead row does not hold back newer versions, so by the time it is replayed a newer version may be
// delivered, or in flight right now, and then the replayed row waits behind it. The replayed
// version is therefore delivered after every version accepted before the replay, and the
// forward-only supersede chain handles it like any other late arrival of an old version.
//
// A row that died after it was prepared goes back to prepared, not pending: its ledger rows and
// prepared records are committed, and a prepared row is never prepared again.
//
// A DELIVERED row is replayable too, and only while one of its records is a dead letter. That is
// the other half of the per-record dead letter: a delivery whose batch held one refusal finished
// as delivered, so without this clause the refused record could never be offered again, and the
// promise of architecture section 11 would be a dead letter nothing can replay. The row comes
// back prepared (it has a prepared_at), and ReviveDeadRecords brings its dead records back in
// the same transaction; the records that landed stay delivered and are not sent again. A
// delivered row with no dead record is not replayable: there is nothing left to offer, and
// making it claimable again would deliver a finished delivery for nothing.
func (q *Queries) Replay(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, replay, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retry = `-- name: Retry :execrows
UPDATE outbox
   SET next_attempt_at = now() + make_interval(secs => $1::float8),
       last_error = $2, lease_until = NULL, lease_token = NULL
 WHERE id = $3 AND lease_token = $4::text AND state IN ('pending', 'prepared')
`

type RetryParams struct {
	DelaySeconds float64
	LastError    string
	ID           string
	LeaseToken   string
}

// The state is kept: a prepared row retries its delivery, it does not prepare again. The row stays
// the head of its key, so nothing behind it moves while it waits.
func (q *Queries) Retry(ctx context.Context, arg RetryParams) (int64, error) {
	result, err := q.db.Exec(ctx, retry,
		arg.DelaySeconds,
		arg.LastError,
		arg.ID,
		arg.LeaseToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reviveDeadRecords = `-- name: ReviveDeadRecords :execrows
UPDATE outbox_record
   SET state = 'prepared', dead_reason = '', last_error = '', finished_at = NULL
 WHERE outbox_id = $1 AND state = 'dead'
`

// Replay for the per-record dead letters of one delivery: they go back to prepared and are
// offered again. Runs in Replay's transaction, after the row itself has been made claimable.
func (q *Queries) ReviveDeadRecords(ctx context.Context, outboxID string) (int64, error) {
	result, err := q.db.Exec(ctx, reviveDeadRecords, outboxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const storePreparedRecords = `-- name: StorePreparedRecords :exec

INSERT INTO outbox_record (outbox_id, record_id, pos, document, op, kind)
SELECT $1, r.record_id, (r.n - 1)::int, d.document, o.op, k.kind
  FROM unnest($2::text[]) WITH ORDINALITY AS r(record_id, n)
  JOIN unnest($3::bytea[]) WITH ORDINALITY AS d(document, n) USING (n)
  JOIN unnest($4::text[]) WITH ORDINALITY AS o(op, n) USING (n)
  JOIN unnest($5::text[]) WITH ORDINALITY AS k(kind, n) USING (n)
`

type StorePreparedRecordsParams struct {
	OutboxID  string
	RecordIds []string
	Documents [][]byte
	Ops       []string
	Kinds     []string
}

// The statements below work the records of one delivery (outbox_record). They all run bound to
// the row's tenant, as the application role: the table carries no tenant of its own and its
// policy asks the delivery's row for one, so a statement with the wrong tenant bound, or none,
// reaches no row at all.
// The records of one delivery, in the order they must be delivered. One statement for a whole
// delivery, not one per record, and the position comes from the array's own ordinality so that
// nothing has to be numbered twice.
//
// It runs after MarkPrepared, which holds the lease and the state: a worker whose lease was taken
// over is refused there and never reaches this, so two workers cannot both store the records of
// one delivery and meet on the primary key.
func (q *Queries) StorePreparedRecords(ctx context.Context, arg StorePreparedRecordsParams) error {
	_, err := q.db.Exec(ctx, storePreparedRecords,
		arg.OutboxID,
		arg.RecordIds,
		arg.Documents,
		arg.Ops,
		arg.Kinds,
	)
	return err
}

const strandedKeys = `-- name: StrandedKeys :many
SELECT u.ordering_key
  FROM outbox u
 WHERE u.tenant_id = $1::text
   AND u.state IN ('pending', 'prepared')
   AND NOT u.is_head
   AND NOT EXISTS (
         SELECT 1
           FROM outbox h
          WHERE h.tenant_id = u.tenant_id
            AND h.ordering_key = u.ordering_key
            AND h.is_head
       )
 GROUP BY u.ordering_key
 ORDER BY u.ordering_key
 LIMIT $2
`

type StrandedKeysParams struct {
	TenantID string
	MaxKeys  int32
}

// Detection, not part of any delivery path. The ordering keys of one tenant that have unfinished
// rows and NO head: the one broken state that is silent, because nothing of such a key is ever
// claimed and nothing fails. (The other ways to break the marker are refused by the table: two
// heads, and a finished head.) This package never produces it. A writer that does not come through
// this package can, and so could a bug in a later change. The repair is in ADR 10.
//
// Runs bound to the tenant, as the application role. It cannot run as the worker role, which
// deliberately reads neither the state nor the ordering key of a row.
//
// It reads the tenant's unfinished rows from outbox_unfinished, in key order, and for each that is
// not a head asks outbox_one_head whether the key has one. So it costs the tenant's backlog, not
// the table, and never touches the delivered history. Measured on 4,000,000 rows: 36 ms and 67,631
// buffers for a tenant with 99,100 unfinished rows, 90,000 of them behind 20 heads, and 2 ms for a
// tenant with 9,100. One statement is one snapshot, and every writer of this package leaves the
// invariant intact when it commits, so a key reported here is broken, not merely in the middle of
// being written.
func (q *Queries) StrandedKeys(ctx context.Context, arg StrandedKeysParams) ([]string, error) {
	rows, err := q.db.Query(ctx, strandedKeys, arg.TenantID, arg.MaxKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ordering_key string
		if err := rows.Scan(&ordering_key); err != nil {
			return nil, err
		}
		items = append(items, ordering_key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const work = `-- name: Work :one
SELECT provider, state, (CASE WHEN state = 'pending' THEN raw_body END)::bytea AS raw_body
  FROM outbox
 WHERE id = $1
`

type WorkRow struct {
	Provider string
	State    string
	RawBody  []byte
}

// What a claim needs in order to work its row, in one statement: the provider the delivery was
// accepted under, the state it is in, and the stored body.
//
// The body comes back only for a row that has not been prepared yet. A prepared row is delivered
// from the records it stored and is never read again (architecture 3.2, step 7), so reading its
// raw_body would be up to a megabyte of a webhook body fetched on every re-drain and every halt,
// for nothing.
//
// Runs bound to the row's tenant, as the application role. The worker role cannot run it: it is
// granted neither raw_body nor state, which is the point of the two-transaction drain.
func (q *Queries) Work(ctx context.Context, id string) (WorkRow, error) {
	row := q.db.QueryRow(ctx, work, id)
	var i WorkRow
	err := row.Scan(&i.Provider, &i.State, &i.RawBody)
	return i, err
}
