package ids

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"os"
	"testing"

	"github.com/zeebo/blake3"
)

var update = flag.Bool("update", false, "rewrite the expected values in testdata/golden.json")

const goldenPath = "testdata/golden.json"

// golden is the on-disk shape of the test vectors. Bodies are hex so that the exact bytes,
// including whitespace and non-UTF-8, survive the JSON round trip.
type golden struct {
	Comment  string           `json:"_comment"`
	Delivery []goldenDelivery `json:"delivery_id"`
	Record   []goldenRecord   `json:"record_id"`
}

type goldenDelivery struct {
	Provider string `json:"provider"`
	BodyHex  string `json:"body_hex"`
	Want     string `json:"want"`
}

type goldenRecord struct {
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
	Version    string `json:"version"`
	Tenant     string `json:"tenant"`
	Want       string `json:"want"`
}

func TestGolden(t *testing.T) {
	raw, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatal(err)
	}
	var g golden
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatal(err)
	}
	if len(g.Delivery) == 0 || len(g.Record) == 0 {
		t.Fatal("golden file has no vectors")
	}

	for i, v := range g.Delivery {
		body, err := hex.DecodeString(v.BodyHex)
		if err != nil {
			t.Fatalf("delivery_id[%d]: bad body_hex: %v", i, err)
		}
		got, err := DeliveryID(v.Provider, body)
		if err != nil {
			t.Fatalf("delivery_id[%d]: %v", i, err)
		}
		if *update {
			g.Delivery[i].Want = got
		} else if got != v.Want {
			t.Errorf("delivery_id[%d] = %s, want %s", i, got, v.Want)
		}
	}

	for i, v := range g.Record {
		got, err := RecordID(v.Provider, v.ExternalID, v.Version, v.Tenant)
		if err != nil {
			t.Fatalf("record_id[%d]: %v", i, err)
		}
		if *update {
			g.Record[i].Want = got
		} else if got != v.Want {
			t.Errorf("record_id[%d] = %s, want %s", i, got, v.Want)
		}
	}

	if *update {
		out, err := json.MarshalIndent(g, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(goldenPath, append(out, '\n'), 0o600); err != nil {
			t.Fatal(err)
		}
	}
}

// The golden file is generated by this package, so on its own it only proves the recipes have not
// changed. This pins the hash underneath to the published BLAKE3 vector for empty input.
func TestHashIsBLAKE3(t *testing.T) {
	const emptyInput = "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262"
	sum := blake3.Sum256(nil)
	if got := hex.EncodeToString(sum[:]); got != emptyInput {
		t.Fatalf("blake3(\"\") = %s, want %s", got, emptyInput)
	}
}

func TestSeparatorKeepsPartBoundaries(t *testing.T) {
	a, err := RecordID("slack", "ab", "c", "tenant_1")
	if err != nil {
		t.Fatal(err)
	}
	b, err := RecordID("slack", "a", "bc", "tenant_1")
	if err != nil {
		t.Fatal(err)
	}
	if a == b {
		t.Errorf(`("ab","c") and ("a","bc") share the id %s`, a)
	}

	d1, _ := DeliveryID("ab", []byte("c"))
	d2, _ := DeliveryID("a", []byte("bc"))
	if d1 == d2 {
		t.Errorf(`delivery ("ab","c") and ("a","bc") share the id %s`, d1)
	}
}

func TestTenantSaltsTheRecordID(t *testing.T) {
	a, err := RecordID("clickup", "task:86a1", "1752064245000", "tenant_a")
	if err != nil {
		t.Fatal(err)
	}
	b, err := RecordID("clickup", "task:86a1", "1752064245000", "tenant_b")
	if err != nil {
		t.Fatal(err)
	}
	if a == b {
		t.Errorf("two tenants share the record id %s", a)
	}
}

func TestRecordIDIsDeterministicAndVersioned(t *testing.T) {
	a, _ := RecordID("slack", "slack:C0GENERAL:1752064245.000200", "1752064245.000200", "tenant_a")
	b, _ := RecordID("slack", "slack:C0GENERAL:1752064245.000200", "1752064245.000200", "tenant_a")
	c, _ := RecordID("slack", "slack:C0GENERAL:1752064245.000200", "1752064300.000100", "tenant_a")
	if a != b {
		t.Errorf("same input gave %s and %s", a, b)
	}
	if a == c {
		t.Error("a new version kept the old record id")
	}
	if !IsRecordID(a) {
		t.Errorf("IsRecordID(%q) = false", a)
	}
}

func TestDeliveryIDHashesTheExactBytes(t *testing.T) {
	// Same JSON value, different bytes. A provider's re-send is byte-identical, so anything that
	// differs is a different delivery; collapsing the two is the record id's job, not this one's.
	a, _ := DeliveryID("clickup", []byte(`{"a":1}`))
	b, _ := DeliveryID("clickup", []byte(`{"a": 1}`))
	if a == b {
		t.Error("whitespace-different bodies share a delivery id")
	}
	if len(a) != 64 {
		t.Errorf("delivery id length = %d, want 64", len(a))
	}
}

func TestBadPartsAreRefused(t *testing.T) {
	tests := []struct {
		name  string
		parts [4]string
		want  error
	}{
		{"empty provider", [4]string{"", "x", "1", "t"}, ErrEmptyPart},
		{"empty external id", [4]string{"slack", "", "1", "t"}, ErrEmptyPart},
		{"empty version", [4]string{"slack", "x", "", "t"}, ErrEmptyPart},
		{"empty tenant", [4]string{"slack", "x", "1", ""}, ErrEmptyPart},
		{"separator in external id", [4]string{"slack", "a\x1fb", "1", "t"}, ErrSeparatorInPart},
		{"separator in tenant", [4]string{"slack", "x", "1", "t\x1f"}, ErrSeparatorInPart},
	}
	for _, tt := range tests {
		got, err := RecordID(tt.parts[0], tt.parts[1], tt.parts[2], tt.parts[3])
		if !errors.Is(err, tt.want) {
			t.Errorf("%s: err = %v, want %v", tt.name, err, tt.want)
		}
		if got != "" {
			t.Errorf("%s: returned the id %q alongside an error", tt.name, got)
		}
	}

	if _, err := DeliveryID("", []byte("x")); !errors.Is(err, ErrEmptyPart) {
		t.Errorf("DeliveryID with no provider: err = %v", err)
	}
	if _, err := DeliveryID("sl\x1fack", []byte("x")); !errors.Is(err, ErrSeparatorInPart) {
		t.Errorf("DeliveryID with a separator in the provider: err = %v", err)
	}
	// The body is the last part, so a separator inside it is unambiguous and allowed.
	if _, err := DeliveryID("slack", []byte("a\x1fb")); err != nil {
		t.Errorf("DeliveryID refused a body containing 0x1F: %v", err)
	}
}

func TestIsRecordID(t *testing.T) {
	for s, want := range map[string]bool{
		"rec_4be29c01d7f3a8e64f0d2b91c6e75a30":  true,
		"rec_4BE29C01D7F3A8E64F0D2B91C6E75A30":  false,
		"rec_4be29c01d7f3a8e64f0d2b91c6e75a3":   false,
		"rec_4be29c01d7f3a8e64f0d2b91c6e75a300": false,
		"4be29c01d7f3a8e64f0d2b91c6e75a30":      false,
		"rec_4be29c01d7f3a8e64f0d2b91c6e75a3g":  false,
		"":                                      false,
	} {
		if got := IsRecordID(s); got != want {
			t.Errorf("IsRecordID(%q) = %v, want %v", s, got, want)
		}
	}
}

func TestNewIsUnique(t *testing.T) {
	seen := make(map[string]bool)
	for range 1000 {
		id := New()
		if len(id) != 26 {
			t.Fatalf("New() = %q, want 26 characters", id)
		}
		if seen[id] {
			t.Fatalf("New() repeated %q", id)
		}
		seen[id] = true
	}
}
