package ids

import (
	"encoding/hex"
	"encoding/json"
	"errors"
	"flag"
	"os"
	"regexp"
	"sync"
	"testing"

	"github.com/zeebo/blake3"
)

var update = flag.Bool("update", false, "rewrite the expected values in testdata/golden.json")

const goldenPath = "testdata/golden.json"

// golden is the on-disk shape of the test vectors. Bodies are hex so that the exact bytes,
// including whitespace and non-UTF-8, survive the JSON round trip.
type golden struct {
	Comment  string           `json:"_comment"`
	Delivery []goldenDelivery `json:"delivery_id"`
	Record   []goldenRecord   `json:"record_id"`
}

type goldenDelivery struct {
	Provider string `json:"provider"`
	BodyHex  string `json:"body_hex"`
	Want     string `json:"want"`
}

type goldenRecord struct {
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
	Version    string `json:"version"`
	Scope      string `json:"scope"`
	Tenant     string `json:"tenant"`
	Want       string `json:"want"`
}

func TestGolden(t *testing.T) {
	raw, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatal(err)
	}
	var g golden
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatal(err)
	}
	if len(g.Delivery) == 0 || len(g.Record) == 0 {
		t.Fatal("golden file has no vectors")
	}

	for i, v := range g.Delivery {
		body, err := hex.DecodeString(v.BodyHex)
		if err != nil {
			t.Fatalf("delivery_id[%d]: bad body_hex: %v", i, err)
		}
		got, err := DeliveryID(v.Provider, body)
		if err != nil {
			t.Fatalf("delivery_id[%d]: %v", i, err)
		}
		if *update {
			g.Delivery[i].Want = got
		} else if got != v.Want {
			t.Errorf("delivery_id[%d] = %s, want %s", i, got, v.Want)
		}
	}

	for i, v := range g.Record {
		got, err := RecordID(v.Provider, v.ExternalID, v.Version, v.Scope, v.Tenant)
		if err != nil {
			t.Fatalf("record_id[%d]: %v", i, err)
		}
		if *update {
			g.Record[i].Want = got
		} else if got != v.Want {
			t.Errorf("record_id[%d] = %s, want %s", i, got, v.Want)
		}
	}

	if *update {
		out, err := json.MarshalIndent(g, "", "  ")
		if err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(goldenPath, append(out, '\n'), 0o600); err != nil {
			t.Fatal(err)
		}
	}
}

// BLAKE3 hashes 1024 byte chunks into a tree, and implementations switch code paths again at
// 8192 bytes. An implementation with a wrong chunk counter agrees on every short input, so the
// golden file has to carry inputs on both sides of each boundary, and real webhook bodies are that
// large. This keeps those vectors from being dropped, and keeps the file's description of how
// their bodies are generated true.
func TestGoldenCoversMultiChunkInputs(t *testing.T) {
	raw, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatal(err)
	}
	var g golden
	if err := json.Unmarshal(raw, &g); err != nil {
		t.Fatal(err)
	}

	// Hash input lengths (provider, separator, body) that must each be present.
	want := map[int]string{
		1024:  "exactly one chunk",
		1025:  "one byte into the second chunk",
		8201:  "past 8192 bytes",  // "clickup" + 0x1F + 8193
		16393: "past 16384 bytes", // "outlook" + 0x1F + 16385
	}
	for i, v := range g.Delivery {
		body, err := hex.DecodeString(v.BodyHex)
		if err != nil {
			t.Fatalf("delivery_id[%d]: bad body_hex: %v", i, err)
		}
		delete(want, len(v.Provider)+1+len(body))
		if len(body) < 1000 {
			continue
		}
		for j, b := range body {
			if b != byte(j%251) {
				t.Fatalf("delivery_id[%d]: body byte %d is %#x, but the file says large bodies are i mod 251", i, j, b)
			}
		}
	}
	for n, why := range want {
		t.Errorf("no delivery_id vector with a %d byte hash input (%s)", n, why)
	}
}

// The golden file is generated by this package, so on its own it only proves the recipes have not
// changed. This pins the hash underneath to the published BLAKE3 vector for empty input.
func TestHashIsBLAKE3(t *testing.T) {
	const emptyInput = "af1349b9f5f9a1a6a0404dea36dcc9499bcb25c9adc112b7cc9a93cae41f3262"
	sum := blake3.Sum256(nil)
	if got := hex.EncodeToString(sum[:]); got != emptyInput {
		t.Fatalf("blake3(\"\") = %s, want %s", got, emptyInput)
	}
}

func TestSeparatorKeepsPartBoundaries(t *testing.T) {
	// Every boundary between two neighbouring parts, the scope's two included.
	shifted := [][2][5]string{
		{{"ab", "c", "v", "s", "t"}, {"a", "bc", "v", "s", "t"}},
		{{"p", "ab", "c", "s", "t"}, {"p", "a", "bc", "s", "t"}},
		{{"p", "x", "ab", "c", "t"}, {"p", "x", "a", "bc", "t"}},
		{{"p", "x", "v", "ab", "c"}, {"p", "x", "v", "a", "bc"}},
	}
	for _, pair := range shifted {
		a, err := RecordID(pair[0][0], pair[0][1], pair[0][2], pair[0][3], pair[0][4])
		if err != nil {
			t.Fatal(err)
		}
		b, err := RecordID(pair[1][0], pair[1][1], pair[1][2], pair[1][3], pair[1][4])
		if err != nil {
			t.Fatal(err)
		}
		if a == b {
			t.Errorf("%q and %q share the id %s", pair[0], pair[1], a)
		}
	}

	d1, _ := DeliveryID("ab", []byte("c"))
	d2, _ := DeliveryID("a", []byte("bc"))
	if d1 == d2 {
		t.Errorf(`delivery ("ab","c") and ("a","bc") share the id %s`, d1)
	}
}

func TestTenantSaltsTheRecordID(t *testing.T) {
	a, err := RecordID("clickup", "task:86a1", "1752064245000", "clickup:list:901100", "tenant_a")
	if err != nil {
		t.Fatal(err)
	}
	b, err := RecordID("clickup", "task:86a1", "1752064245000", "clickup:list:901100", "tenant_b")
	if err != nil {
		t.Fatal(err)
	}
	if a == b {
		t.Errorf("two tenants share the record id %s", a)
	}
}

// A task moved to another list is decided on another scope. Its provider version may not change
// with the move, and the record must still be a new one, or the ledger skips it as delivered and
// the sink keeps the old scope (ADR 4).
func TestScopeIsPartOfTheRecordID(t *testing.T) {
	before, err := RecordID("clickup", "task:86a1", "1752064245000", "clickup:list:901100", "tenant_a")
	if err != nil {
		t.Fatal(err)
	}
	after, err := RecordID("clickup", "task:86a1", "1752064245000", "clickup:list:901200", "tenant_a")
	if err != nil {
		t.Fatal(err)
	}
	if before == after {
		t.Errorf("a move to another scope kept the record id %s", before)
	}
}

func TestRecordIDIsDeterministicAndVersioned(t *testing.T) {
	const scope = "slack:channel:C0GENERAL"
	a, _ := RecordID("slack", "slack:C0GENERAL:1752064245.000200", "1752064245.000200", scope, "tenant_a")
	b, _ := RecordID("slack", "slack:C0GENERAL:1752064245.000200", "1752064245.000200", scope, "tenant_a")
	c, _ := RecordID("slack", "slack:C0GENERAL:1752064245.000200", "1752064300.000100", scope, "tenant_a")
	if a != b {
		t.Errorf("same input gave %s and %s", a, b)
	}
	if a == c {
		t.Error("a new version kept the old record id")
	}
	if !recordIDShape.MatchString(a) {
		t.Errorf("RecordID = %q, want the shape %s", a, recordIDShape)
	}
}

// recordIDShape is the documented shape: the prefix, then 32 lowercase hex characters.
var recordIDShape = regexp.MustCompile(`^rec_[0-9a-f]{32}$`)

func TestDeliveryIDHashesTheExactBytes(t *testing.T) {
	// Same JSON value, different bytes. A provider's re-send is byte-identical, so anything that
	// differs is a different delivery; collapsing the two is the record id's job, not this one's.
	a, _ := DeliveryID("clickup", []byte(`{"a":1}`))
	b, _ := DeliveryID("clickup", []byte(`{"a": 1}`))
	if a == b {
		t.Error("whitespace-different bodies share a delivery id")
	}
	if len(a) != 64 {
		t.Errorf("delivery id length = %d, want 64", len(a))
	}
}

func TestBadPartsAreRefused(t *testing.T) {
	tests := []struct {
		name  string
		parts [5]string
		want  error
	}{
		{"empty provider", [5]string{"", "x", "1", "s", "t"}, ErrEmptyPart},
		{"empty external id", [5]string{"slack", "", "1", "s", "t"}, ErrEmptyPart},
		{"empty version", [5]string{"slack", "x", "", "s", "t"}, ErrEmptyPart},
		{"empty scope", [5]string{"slack", "x", "1", "", "t"}, ErrEmptyPart},
		{"empty tenant", [5]string{"slack", "x", "1", "s", ""}, ErrEmptyPart},
		{"separator in external id", [5]string{"slack", "a\x1fb", "1", "s", "t"}, ErrSeparatorInPart},
		{"separator in scope", [5]string{"slack", "x", "1", "s\x1f", "t"}, ErrSeparatorInPart},
		{"separator in tenant", [5]string{"slack", "x", "1", "s", "t\x1f"}, ErrSeparatorInPart},
	}
	for _, tt := range tests {
		got, err := RecordID(tt.parts[0], tt.parts[1], tt.parts[2], tt.parts[3], tt.parts[4])
		if !errors.Is(err, tt.want) {
			t.Errorf("%s: err = %v, want %v", tt.name, err, tt.want)
		}
		if got != "" {
			t.Errorf("%s: returned the id %q alongside an error", tt.name, got)
		}
	}

	if _, err := DeliveryID("", []byte("x")); !errors.Is(err, ErrEmptyPart) {
		t.Errorf("DeliveryID with no provider: err = %v", err)
	}
	if _, err := DeliveryID("sl\x1fack", []byte("x")); !errors.Is(err, ErrSeparatorInPart) {
		t.Errorf("DeliveryID with a separator in the provider: err = %v", err)
	}
	// The body is the last part, so a separator inside it is unambiguous and allowed.
	if _, err := DeliveryID("slack", []byte("a\x1fb")); err != nil {
		t.Errorf("DeliveryID refused a body containing 0x1F: %v", err)
	}
}

func TestNewIsUnique(t *testing.T) {
	seen := make(map[string]bool)
	for range 1000 {
		id := New()
		if len(id) != 26 {
			t.Fatalf("New() = %q, want 26 characters", id)
		}
		if seen[id] {
			t.Fatalf("New() repeated %q", id)
		}
		seen[id] = true
	}
}

func TestNewIsUniqueAcrossGoroutines(t *testing.T) {
	// The outbox workers call New concurrently. Under -race this pins that the entropy source
	// behind it is locked, and the duplicate check pins that the lock covers the monotonic step:
	// most of these ids share a millisecond, which is exactly where an unlocked source repeats.
	const workers, each = 16, 500

	minted := make([][]string, workers)
	var wg sync.WaitGroup
	for w := range workers {
		wg.Add(1)
		go func() {
			defer wg.Done()
			out := make([]string, each)
			for i := range out {
				out[i] = New()
			}
			minted[w] = out
		}()
	}
	wg.Wait()

	seen := make(map[string]bool, workers*each)
	for _, out := range minted {
		for _, id := range out {
			if len(id) != 26 {
				t.Fatalf("New() = %q, want 26 characters", id)
			}
			if seen[id] {
				t.Fatalf("New() repeated %q across goroutines", id)
			}
			seen[id] = true
		}
	}
}
