// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package pipelinedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const demoteEntityHead = `-- name: DemoteEntityHead :exec
UPDATE record_ledger
   SET is_head = false
 WHERE tenant_id = $1
   AND provider = $2
   AND external_id = $3
   AND is_head
`

type DemoteEntityHeadParams struct {
	TenantID   string
	Provider   string
	ExternalID string
}

// Takes the head marker off the entity's current head, so the new record can take it. Runs under
// LockEntity, in the same statement order every time.
func (q *Queries) DemoteEntityHead(ctx context.Context, arg DemoteEntityHeadParams) error {
	_, err := q.db.Exec(ctx, demoteEntityHead, arg.TenantID, arg.Provider, arg.ExternalID)
	return err
}

const entityHead = `-- name: EntityHead :one
SELECT record_id, version, scope
  FROM record_ledger
 WHERE tenant_id = $1
   AND provider = $2
   AND external_id = $3
   AND is_head
`

type EntityHeadParams struct {
	TenantID   string
	Provider   string
	ExternalID string
}

type EntityHeadRow struct {
	RecordID string
	Version  string
	Scope    string
}

// The newest record prepared for one entity: what a new record supersedes, and the scope the move
// detection of ADR 4 decision 7 compares against. No row means the entity has nothing prepared.
//
// It is an equality probe on the whole of record_ledger_one_head, which holds only the heads.
func (q *Queries) EntityHead(ctx context.Context, arg EntityHeadParams) (EntityHeadRow, error) {
	row := q.db.QueryRow(ctx, entityHead, arg.TenantID, arg.Provider, arg.ExternalID)
	var i EntityHeadRow
	err := row.Scan(&i.RecordID, &i.Version, &i.Scope)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :exec
INSERT INTO record_ledger
  (tenant_id, record_id, provider, external_id, version, scope, supersedes, is_head)
VALUES
  ($1, $2, $3, $4, $5, $6, $7, true)
`

type InsertLedgerEntryParams struct {
	TenantID   string
	RecordID   string
	Provider   string
	ExternalID string
	Version    string
	Scope      string
	Supersedes pgtype.Text
}

// Records a record as prepared and as its entity's head. Runs under LockEntity, after
// DemoteEntityHead, so record_ledger_one_head is satisfied within the transaction.
//
// A repeat cannot reach this statement: the caller has already asked LedgerEntry, and a record id
// it knows is skipped or dead-lettered rather than inserted. If one ever did, the primary key
// refuses it rather than storing a second copy.
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) error {
	_, err := q.db.Exec(ctx, insertLedgerEntry,
		arg.TenantID,
		arg.RecordID,
		arg.Provider,
		arg.ExternalID,
		arg.Version,
		arg.Scope,
		arg.Supersedes,
	)
	return err
}

const ledgerEntry = `-- name: LedgerEntry :one
SELECT record_id, is_head, scope
  FROM record_ledger
 WHERE tenant_id = $1
   AND record_id = $2
`

type LedgerEntryParams struct {
	TenantID string
	RecordID string
}

type LedgerEntryRow struct {
	RecordID string
	IsHead   bool
	Scope    string
}

// Whether this record id has already been prepared, and whether it is still its entity's head.
// Those are conditions 1 and 2 of ADR 4 decision 7. A primary key lookup.
func (q *Queries) LedgerEntry(ctx context.Context, arg LedgerEntryParams) (LedgerEntryRow, error) {
	row := q.db.QueryRow(ctx, ledgerEntry, arg.TenantID, arg.RecordID)
	var i LedgerEntryRow
	err := row.Scan(&i.RecordID, &i.IsHead, &i.Scope)
	return i, err
}

const lockEntity = `-- name: LockEntity :exec
SELECT pg_advisory_xact_lock(
  hashtextextended($1::text || chr(31) || $2::text || chr(31) || $3::text, 0))
`

type LockEntityParams struct {
	TenantID   string
	Provider   string
	ExternalID string
}

// Serializes the readers and writers of one entity's supersede chain. The pipeline reads the head,
// demotes it and inserts a new head, and two transactions doing that for one entity at once can
// corrupt the chain without violating a single constraint: both read head X, the first demotes X
// and makes A the head, and the second then demotes A and makes B the head with supersedes = X. X
// would be superseded twice and A would be orphaned in the middle of the chain.
//
// The unique index catches the common interleaving, where the second transaction demotes before
// the first has committed and then finds a head already there. It cannot catch that one: by the
// time the second transaction demotes, the head it takes the marker from is a row it never read,
// so nothing is violated and the chain is quietly wrong. So the entity is locked before it is read,
// for the whole transaction, exactly as internal/outbox locks an ordering key before it assigns a
// seq.
//
// It must be its own statement, before the read: under READ COMMITTED the next statement takes a
// new snapshot, so the waiter sees what the holder committed. store begins every transaction READ
// COMMITTED by name for that reason.
//
// In the ordinary case there is nothing to wait for. The outbox already delivers one entity's
// versions one at a time, in arrival order, because they share an ordering key and only the head
// of a key is ever claimable (ADR 10, ADR 11): that FIFO is what makes arrival order a usable
// order for two records that carry the same provider version. This lock is the second line of
// defense, for the shapes the ordering key does not cover: one entity reached through two
// subscriptions of one tenant, and a reconciliation pass running beside the live feed.
//
// Two entities whose lock strings hash alike only wait for each other, which is harmless.
func (q *Queries) LockEntity(ctx context.Context, arg LockEntityParams) error {
	_, err := q.db.Exec(ctx, lockEntity, arg.TenantID, arg.Provider, arg.ExternalID)
	return err
}

const upsertRedactions = `-- name: UpsertRedactions :many
INSERT INTO redaction_map (tenant_id, token, kind, value)
SELECT $1::text, tok.token, knd.kind, val.value
  FROM unnest($2::text[]) WITH ORDINALITY AS tok(token, n)
  JOIN unnest($3::text[])  WITH ORDINALITY AS knd(kind, n)  USING (n)
  JOIN unnest($4::text[]) WITH ORDINALITY AS val(value, n) USING (n)
ON CONFLICT ON CONSTRAINT redaction_map_one_token_per_value
DO UPDATE SET last_seen_at = now()
RETURNING token, kind, value
`

type UpsertRedactionsParams struct {
	TenantID string
	Tokens   []string
	Kinds    []string
	Values   []string
}

type UpsertRedactionsRow struct {
	Token string
	Kind  string
	Value string
}

// Gives every (kind, value) the masker found the token that stands for it: the one it already had,
// or the one this statement stores for it now.
//
// One statement for a whole delivery, not one per value: the masker collects everything it found
// first, so nothing here runs in a loop however many addresses a text holds.
//
// ON CONFLICT DO UPDATE and not DO NOTHING, because DO NOTHING returns no row for a value that is
// already mapped and the caller needs that value's existing token. The update writes last_seen_at,
// which is the column an operator prunes the map by.
func (q *Queries) UpsertRedactions(ctx context.Context, arg UpsertRedactionsParams) ([]UpsertRedactionsRow, error) {
	rows, err := q.db.Query(ctx, upsertRedactions,
		arg.TenantID,
		arg.Tokens,
		arg.Kinds,
		arg.Values,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UpsertRedactionsRow
	for rows.Next() {
		var i UpsertRedactionsRow
		if err := rows.Scan(&i.Token, &i.Kind, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
